package com.wts.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLoan<M extends BaseLoan<M>> extends Model<M> implements IBean {

	/**
	 * 序号
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 序号
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 办理地
	 */
	public M setDepartmentId(java.lang.Integer departmentId) {
		set("department_id", departmentId);
		return (M)this;
	}
	
	/**
	 * 办理地
	 */
	public java.lang.Integer getDepartmentId() {
		return getInt("department_id");
	}

	/**
	 * 办理银行
	 */
	public M setBankId(java.lang.Integer bankId) {
		set("bank_id", bankId);
		return (M)this;
	}
	
	/**
	 * 办理银行
	 */
	public java.lang.Integer getBankId() {
		return getInt("bank_id");
	}

	/**
	 * 证件类型
	 */
	public M setTypeId(java.lang.Integer typeId) {
		set("type_id", typeId);
		return (M)this;
	}
	
	/**
	 * 证件类型
	 */
	public java.lang.Integer getTypeId() {
		return getInt("type_id");
	}

	/**
	 * 申报时间
	 */
	public M setTime(java.lang.Integer time) {
		set("time", time);
		return (M)this;
	}
	
	/**
	 * 申报时间
	 */
	public java.lang.Integer getTime() {
		return getInt("time");
	}

	/**
	 * 贷款金额万元
	 */
	public M setMoney(java.lang.Integer money) {
		set("money", money);
		return (M)this;
	}
	
	/**
	 * 贷款金额万元
	 */
	public java.lang.Integer getMoney() {
		return getInt("money");
	}

	/**
	 * 贷款期限
	 */
	public M setMonth(java.lang.Integer month) {
		set("month", month);
		return (M)this;
	}
	
	/**
	 * 贷款期限
	 */
	public java.lang.Integer getMonth() {
		return getInt("month");
	}

	/**
	 * 贴息比例
	 */
	public M setBase(java.lang.Integer base) {
		set("base", base);
		return (M)this;
	}
	
	/**
	 * 贴息比例
	 */
	public java.lang.Integer getBase() {
		return getInt("base");
	}

	/**
	 * 贷款状态1未处理2被退回3已审批4已放款5已回款
	 */
	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	/**
	 * 贷款状态1未处理2被退回3已审批4已放款5已回款
	 */
	public java.lang.Integer getState() {
		return getInt("state");
	}

	/**
	 * 营业执照名称
	 */
	public M setBusiness(java.lang.String business) {
		set("business", business);
		return (M)this;
	}
	
	/**
	 * 营业执照名称
	 */
	public java.lang.String getBusiness() {
		return getStr("business");
	}

	/**
	 * 经营场所
	 */
	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}
	
	/**
	 * 经营场所
	 */
	public java.lang.String getAddress() {
		return getStr("address");
	}

	/**
	 * 经营项目
	 */
	public M setProject(java.lang.String project) {
		set("project", project);
		return (M)this;
	}
	
	/**
	 * 经营项目
	 */
	public java.lang.String getProject() {
		return getStr("project");
	}

	/**
	 * 姓名
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 姓名
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 身份证号码
	 */
	public M setNumber(java.lang.String number) {
		set("number", number);
		return (M)this;
	}
	
	/**
	 * 身份证号码
	 */
	public java.lang.String getNumber() {
		return getStr("number");
	}

	/**
	 * 性别0未知1男2女
	 */
	public M setSex(java.lang.Integer sex) {
		set("sex", sex);
		return (M)this;
	}
	
	/**
	 * 性别0未知1男2女
	 */
	public java.lang.Integer getSex() {
		return getInt("sex");
	}

	/**
	 * 出生日期
	 */
	public M setBirth(java.util.Date birth) {
		set("birth", birth);
		return (M)this;
	}
	
	/**
	 * 出生日期
	 */
	public java.util.Date getBirth() {
		return get("birth");
	}

	/**
	 * 婚姻状况1未婚2已婚3离异4丧偶
	 */
	public M setMarriage(java.lang.Integer marriage) {
		set("marriage", marriage);
		return (M)this;
	}
	
	/**
	 * 婚姻状况1未婚2已婚3离异4丧偶
	 */
	public java.lang.Integer getMarriage() {
		return getInt("marriage");
	}

	/**
	 * 联系电话
	 */
	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	/**
	 * 联系电话
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	/**
	 * 配偶姓名
	 */
	public M setSpouse(java.lang.String spouse) {
		set("spouse", spouse);
		return (M)this;
	}
	
	/**
	 * 配偶姓名
	 */
	public java.lang.String getSpouse() {
		return getStr("spouse");
	}

	/**
	 * 配偶电话
	 */
	public M setPhone2(java.lang.String phone2) {
		set("phone2", phone2);
		return (M)this;
	}
	
	/**
	 * 配偶电话
	 */
	public java.lang.String getPhone2() {
		return getStr("phone2");
	}

	/**
	 * 备注
	 */
	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
