package com.wts.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseChange<M extends BaseChange<M>> extends Model<M> implements IBean {

	/**
	 * 序号
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 序号
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 贷款序号
	 */
	public M setLoanId(java.lang.Integer loanId) {
		set("loan_id", loanId);
		return (M)this;
	}
	
	/**
	 * 贷款序号
	 */
	public java.lang.Integer getLoanId() {
		return getInt("loan_id");
	}

	/**
	 * 用户序号
	 */
	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	/**
	 * 用户序号
	 */
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 之前信息
	 */
	public M setBefore(java.lang.String before) {
		set("before", before);
		return (M)this;
	}
	
	/**
	 * 之前信息
	 */
	public java.lang.String getBefore() {
		return getStr("before");
	}

	/**
	 * 之后信息
	 */
	public M setAfter(java.lang.String after) {
		set("after", after);
		return (M)this;
	}
	
	/**
	 * 之后信息
	 */
	public java.lang.String getAfter() {
		return getStr("after");
	}

	/**
	 * 修改时间
	 */
	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getTime() {
		return get("time");
	}

}
