package com.wts.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	/**
	 * 序号
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 序号
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 姓名
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 姓名
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 用户密码
	 */
	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}
	
	/**
	 * 用户密码
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}

	/**
	 * 状态0注销1激活
	 */
	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	/**
	 * 状态0注销1激活
	 */
	public java.lang.Integer getState() {
		return getInt("state");
	}

	/**
	 * 用户名
	 */
	public M setLogin(java.lang.String login) {
		set("login", login);
		return (M)this;
	}
	
	/**
	 * 用户名
	 */
	public java.lang.String getLogin() {
		return getStr("login");
	}

}
