package com.wts.common.model;

import com.wts.common.model.base.BaseDepartment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Department extends BaseDepartment<Department> {
	
}
